name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Directory Structure (debugging)
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing Root Directory:"
          ls -R .

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check Directory Structure (demo/todo/todo)
        run: |
          ls -R demo/todo/todo

      - name: Install Backend Dependencies
        run: |
          echo "Installing backend dependencies in demo/todo/todo/backend"
          cd demo/todo/todo/backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          echo "Installing frontend dependencies in demo/todo/todo/frontend"
          cd demo/todo/todo/frontend
          npm install

      - name: Build Frontend
        run: |
          echo "Building frontend in demo/todo/todo/frontend"
          cd demo/todo/todo/frontend
          npm run build

      - name: Run Backend Tests (optional)
        run: |
          echo "Running backend tests in demo/todo/todo/backend"
          cd demo/todo/todo/backend
          npm test || echo "No tests available"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          echo "Building and pushing Docker images for backend"
          docker build -t aman585/todo-backend ./demo/todo/todo/backend
          echo "Building and pushing Docker images for frontend"
          docker build -t aman585/todo-frontend ./demo/todo/todo/frontend
          docker push aman585/todo-backend
          docker push aman585/todo-frontend
